CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE urls ADD COLUMN user_id INT UNSIGNED NULL;

ALTER TABLE urls ADD CONSTRAINT fk_urls_user
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE SET NULL;